obj = {
    "subCode": "0",
    "msg": "success",
    "biTestId": "1",
    "biDisplayTmpr": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613-560",
    "productGroupList": [
        {
            "groupId": "16998410",
            "groupName": "CKA爆款池",
            "curStageId": "34463614",
            "stageInfoList": [
                {
                    "stageId": "34463614",
                    "groupId": "16998410",
                    "stageName": "CKA爆款池",
                    "stageTime": "2021-09-24 00:00:00",
                    "stageStatus": "0",
                    "remainTime": "0",
                    "productInfoList": [
                        {
                            "productBaseInfo": {
                                "skuId": "10025872835736",
                                "name": "高洁丝臻选系列夜用280毫米13片 1件",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/120701/32/26204/209207/6246d2efEb0f913e8/faed02cc248b37e1.jpg",
                                "picUrl": "jfs/t1/120701/32/26204/209207/6246d2efEb0f913e8/faed02cc248b37e1.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "15.50",
                                "realStock": true,
                                "pPrice": "15.5",
                                "pcpPrice": "25",
                                "showStatus": false,
                                "appDiscount": "比PC端省9.5元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "15.5",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 16800,
                                "venderId": 10509076,
                                "classIdL2": 16754,
                                "classIdL1": 16750,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 38
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MDEiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10025872835736-1000068339#1-0-1014-10509076-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10025872835736-1000068339",
                                "mct": "1-0-1014-10509076-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 7,
                                "storeTag": {
                                    "pickup_code": 0,
                                    "pickup_type": 0,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 1
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t23812/362/2403295549/6879/850c76b1/5b7e1d31Na86b80d0.jpg!cc_80x80",
                                "venderId": 10509076,
                                "storeInitialPrice": "20",
                                "bizStartHours": "09:00",
                                "agingType": 1440,
                                "storeId": 1000068339,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 52983,
                                "addressDetail": "江苏无锡市江阴市澄江街道江阴青果路14号首层屈臣氏",
                                "deliveryBatch": "10:00-20:00",
                                "fastDeliveryDate": "2022-04-20 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "屈臣氏-江阴青果路店"
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10020808473285",
                                "name": "七度空间 特薄夜用卫生巾275mm*10片/包 新老包装随机发货",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/164750/38/23699/809587/61d3e7b4E505f31a5/e3b059c0d6b0a6ea.png",
                                "picUrl": "jfs/t1/164750/38/23699/809587/61d3e7b4E505f31a5/e3b059c0d6b0a6ea.png",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "10.90",
                                "realStock": true,
                                "pPrice": "10.9",
                                "pcpPrice": "17.5",
                                "showStatus": false,
                                "appDiscount": "比PC端省6.6元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "10.9",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 16800,
                                "venderId": 10509076,
                                "classIdL2": 16754,
                                "classIdL1": 16750,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 37
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MDEiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10020808473285-1000068339#1-0-1014-10509076-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10020808473285-1000068339",
                                "mct": "1-0-1014-10509076-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 7,
                                "storeTag": {
                                    "pickup_code": 0,
                                    "pickup_type": 0,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 1
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t23812/362/2403295549/6879/850c76b1/5b7e1d31Na86b80d0.jpg!cc_80x80",
                                "venderId": 10509076,
                                "storeInitialPrice": "20",
                                "bizStartHours": "09:00",
                                "agingType": 1440,
                                "storeId": 1000068339,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 52983,
                                "addressDetail": "江苏无锡市江阴市澄江街道江阴青果路14号首层屈臣氏",
                                "deliveryBatch": "10:00-20:00",
                                "fastDeliveryDate": "2022-04-20 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "屈臣氏-江阴青果路店"
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "69640485110",
                                "name": "福临门黄金产地玉米油4.5升",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/201590/40/15105/50416/618ce697E15017d51/47ef657244836d75.jpg",
                                "picUrl": "jfs/t1/201590/40/15105/50416/618ce697E15017d51/47ef657244836d75.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "75.00",
                                "realStock": true,
                                "pPrice": "75",
                                "pcpPrice": "95",
                                "showStatus": false,
                                "appDiscount": "比PC端省20元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "75",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 2676,
                                "venderId": 10391548,
                                "classIdL2": 1584,
                                "classIdL1": 1320,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 21
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MDEiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-69640485110-1000120851#1-0-1014-10391548-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-69640485110-1000120851",
                                "mct": "1-0-1014-10391548-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 4,
                                "storeTag": {
                                    "effectiveness": 1,
                                    "pickup_code": 0,
                                    "store_dada": 1,
                                    "pickup_type": 3,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 2
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t1/108455/20/9399/94111/5e746da8E0550643f/991cbefda671d00b.jpg!cc_80x80",
                                "venderId": 10391548,
                                "storeInitialPrice": "0",
                                "bizStartHours": "07:30",
                                "agingType": 38,
                                "purchasePrice": "70",
                                "storeId": 1000120851,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 1063,
                                "addressDetail": "江苏无锡市新吴区无锡高新技术产业开发区江苏省无锡市新吴区行创六路7-22",
                                "deliveryBatch": "10:18-11:18",
                                "fastDeliveryDate": "2022-04-19 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "华润万家-新洲花园店",
                                "purchaseNum": 1
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10021782018660",
                                "name": "屈臣氏细滑深洁护理牙线棒50支(独立包装) 50支",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/107783/17/16796/178200/5eb4bc6bEf50f5b3b/6a22760db5a29bd7.jpg",
                                "picUrl": "jfs/t1/107783/17/16796/178200/5eb4bc6bEf50f5b3b/6a22760db5a29bd7.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "8.50",
                                "realStock": true,
                                "pPrice": "8.5",
                                "pcpPrice": "16.9",
                                "showStatus": false,
                                "appDiscount": "比PC端省8.4元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "8.5",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 16810,
                                "venderId": 10509076,
                                "classIdL2": 16755,
                                "classIdL1": 16750,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 49
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MTQiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10021782018660-1000068339#1-0-1014-10509076-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10021782018660-1000068339",
                                "mct": "1-0-1014-10509076-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 7,
                                "storeTag": {
                                    "pickup_code": 0,
                                    "pickup_type": 0,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 1
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t23812/362/2403295549/6879/850c76b1/5b7e1d31Na86b80d0.jpg!cc_80x80",
                                "venderId": 10509076,
                                "storeInitialPrice": "20",
                                "bizStartHours": "09:00",
                                "agingType": 1440,
                                "storeId": 1000068339,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 52983,
                                "addressDetail": "江苏无锡市江阴市澄江街道江阴青果路14号首层屈臣氏",
                                "deliveryBatch": "10:00-20:00",
                                "fastDeliveryDate": "2022-04-20 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "屈臣氏-江阴青果路店"
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10021621063340",
                                "name": "金龙鱼甄选稻米油4.5L",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/157141/21/8/124647/5fe9502fEc9279a5f/ec0a27c16df1ca1d.jpg",
                                "picUrl": "jfs/t1/157141/21/8/124647/5fe9502fEc9279a5f/ec0a27c16df1ca1d.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "69.90",
                                "realStock": true,
                                "pPrice": "69.9",
                                "pcpPrice": "128",
                                "showStatus": false,
                                "appDiscount": "比PC端省58.1元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "69.9",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 2676,
                                "venderId": 10391548,
                                "classIdL2": 1584,
                                "classIdL1": 1320,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 45
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MDMiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10021621063340-1000120851#1-0-1014-10391548-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10021621063340-1000120851",
                                "mct": "1-0-1014-10391548-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 4,
                                "storeTag": {
                                    "effectiveness": 1,
                                    "pickup_code": 0,
                                    "store_dada": 1,
                                    "pickup_type": 3,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 2
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t1/108455/20/9399/94111/5e746da8E0550643f/991cbefda671d00b.jpg!cc_80x80",
                                "venderId": 10391548,
                                "storeInitialPrice": "0",
                                "bizStartHours": "07:30",
                                "agingType": 38,
                                "purchasePrice": "64.9",
                                "storeId": 1000120851,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 1063,
                                "addressDetail": "江苏无锡市新吴区无锡高新技术产业开发区江苏省无锡市新吴区行创六路7-22",
                                "deliveryBatch": "10:18-11:18",
                                "fastDeliveryDate": "2022-04-19 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "华润万家-新洲花园店",
                                "purchaseNum": 1
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10020808499440",
                                "name": "安倍复合维生素软糖240克",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/3213/10/138/187455/5b8f9127E09460328/6d0e34fca2567bbf.jpg",
                                "picUrl": "jfs/t1/3213/10/138/187455/5b8f9127E09460328/6d0e34fca2567bbf.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "15.50",
                                "realStock": true,
                                "pPrice": "15.5",
                                "pcpPrice": "22",
                                "showStatus": false,
                                "appDiscount": "比PC端省6.5元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "15.5",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 2679,
                                "venderId": 10509076,
                                "classIdL2": 1584,
                                "classIdL1": 1320,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 29
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MTQiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10020808499440-1000068339#1-0-1014-10509076-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10020808499440-1000068339",
                                "mct": "1-0-1014-10509076-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 7,
                                "storeTag": {
                                    "pickup_code": 0,
                                    "pickup_type": 0,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 1
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t23812/362/2403295549/6879/850c76b1/5b7e1d31Na86b80d0.jpg!cc_80x80",
                                "venderId": 10509076,
                                "storeInitialPrice": "20",
                                "bizStartHours": "09:00",
                                "agingType": 1440,
                                "storeId": 1000068339,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 52983,
                                "addressDetail": "江苏无锡市江阴市澄江街道江阴青果路14号首层屈臣氏",
                                "deliveryBatch": "10:00-20:00",
                                "promoInfoFieldList": [
                                    {
                                        "promoTags": [
                                            1031
                                        ],
                                        "pid": 148700551795,
                                        "startTime": 1649331540,
                                        "endTime": 1650470340
                                    }
                                ],
                                "fastDeliveryDate": "2022-04-20 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "屈臣氏-江阴青果路店"
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10039781591162",
                                "name": "高老师罐装可可山楂球300g",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/160966/26/26647/118197/617fb376Edf679322/4d7f012696c7327d.jpg",
                                "picUrl": "jfs/t1/160966/26/26647/118197/617fb376Edf679322/4d7f012696c7327d.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "16.90",
                                "realStock": true,
                                "pPrice": "16.9",
                                "pcpPrice": "21.9",
                                "showStatus": false,
                                "appDiscount": "比PC端省5元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "16.9",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 1592,
                                "venderId": 10391548,
                                "classIdL2": 1583,
                                "classIdL1": 1320,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 22
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MTQiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10039781591162-1000120851#1-0-1014-10391548-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10039781591162-1000120851",
                                "mct": "1-0-1014-10391548-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 4,
                                "storeTag": {
                                    "effectiveness": 1,
                                    "pickup_code": 0,
                                    "store_dada": 1,
                                    "pickup_type": 3,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 2
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t1/108455/20/9399/94111/5e746da8E0550643f/991cbefda671d00b.jpg!cc_80x80",
                                "venderId": 10391548,
                                "storeInitialPrice": "0",
                                "bizStartHours": "07:30",
                                "agingType": 38,
                                "purchasePrice": "11.9",
                                "storeId": 1000120851,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 1063,
                                "addressDetail": "江苏无锡市新吴区无锡高新技术产业开发区江苏省无锡市新吴区行创六路7-22",
                                "deliveryBatch": "10:18-11:18",
                                "fastDeliveryDate": "2022-04-19 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "华润万家-新洲花园店",
                                "purchaseNum": 1
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10020808481628",
                                "name": "狮王 齿力佳精致系列酵素美白牙膏(百花薄荷) 130g",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/8680/4/8658/31179/5c0f71adEdf854ed3/d441bf0095b20d01.jpg",
                                "picUrl": "jfs/t1/8680/4/8658/31179/5c0f71adEdf854ed3/d441bf0095b20d01.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "22.00",
                                "realStock": true,
                                "pPrice": "22",
                                "pcpPrice": "29.8",
                                "showStatus": false,
                                "appDiscount": "比PC端省7.8元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "22",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 16806,
                                "venderId": 10509076,
                                "classIdL2": 16755,
                                "classIdL1": 16750,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 26
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MDEiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10020808481628-1000068339#1-0-1014-10509076-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10020808481628-1000068339",
                                "mct": "1-0-1014-10509076-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 7,
                                "storeTag": {
                                    "pickup_code": 0,
                                    "pickup_type": 0,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 1
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t23812/362/2403295549/6879/850c76b1/5b7e1d31Na86b80d0.jpg!cc_80x80",
                                "venderId": 10509076,
                                "storeInitialPrice": "20",
                                "bizStartHours": "09:00",
                                "agingType": 1440,
                                "storeId": 1000068339,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 52983,
                                "addressDetail": "江苏无锡市江阴市澄江街道江阴青果路14号首层屈臣氏",
                                "deliveryBatch": "10:00-20:00",
                                "fastDeliveryDate": "2022-04-20 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "屈臣氏-江阴青果路店"
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10020808512561",
                                "name": "欧莱雅奇焕润发精油(针对受损发质)100ml/瓶 护发",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/192987/16/20931/101913/612dd772E3d16198b/0e866ec22be1eb32.jpg",
                                "picUrl": "jfs/t1/192987/16/20931/101913/612dd772E3d16198b/0e866ec22be1eb32.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "68.90",
                                "realStock": true,
                                "pPrice": "68.9",
                                "pcpPrice": "105",
                                "showStatus": false,
                                "appDiscount": "比PC端省36.1元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "68.9",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 16760,
                                "venderId": 10509076,
                                "classIdL2": 16751,
                                "classIdL1": 16750,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 34
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MTQiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10020808512561-1000068339#1-0-1014-10509076-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10020808512561-1000068339",
                                "mct": "1-0-1014-10509076-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 7,
                                "storeTag": {
                                    "pickup_code": 0,
                                    "pickup_type": 0,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 1
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t23812/362/2403295549/6879/850c76b1/5b7e1d31Na86b80d0.jpg!cc_80x80",
                                "venderId": 10509076,
                                "storeInitialPrice": "20",
                                "bizStartHours": "09:00",
                                "agingType": 1440,
                                "purchasePrice": "52.23",
                                "storeId": 1000068339,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 52983,
                                "addressDetail": "江苏无锡市江阴市澄江街道江阴青果路14号首层屈臣氏",
                                "deliveryBatch": "10:00-20:00",
                                "fastDeliveryDate": "2022-04-20 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "屈臣氏-江阴青果路店",
                                "purchaseNum": 3
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "72332389937",
                                "name": "优至麦香竹炭牙刷四支装",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/123365/27/24869/103702/622ed758E5f54aa63/e8893445448ef4ad.jpg",
                                "picUrl": "jfs/t1/123365/27/24869/103702/622ed758E5f54aa63/e8893445448ef4ad.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "13.90",
                                "realStock": true,
                                "pPrice": "13.9",
                                "pcpPrice": "19.9",
                                "showStatus": false,
                                "appDiscount": "比PC端省6元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "13.9",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 16809,
                                "venderId": 10391548,
                                "classIdL2": 16755,
                                "classIdL1": 16750,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 30
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MDEiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-72332389937-1000120851#1-0-1014-10391548-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-72332389937-1000120851",
                                "mct": "1-0-1014-10391548-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 4,
                                "storeTag": {
                                    "effectiveness": 1,
                                    "pickup_code": 0,
                                    "store_dada": 1,
                                    "pickup_type": 3,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 2
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t1/108455/20/9399/94111/5e746da8E0550643f/991cbefda671d00b.jpg!cc_80x80",
                                "venderId": 10391548,
                                "storeInitialPrice": "0",
                                "bizStartHours": "07:30",
                                "agingType": 38,
                                "purchasePrice": "8.9",
                                "storeId": 1000120851,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 1063,
                                "addressDetail": "江苏无锡市新吴区无锡高新技术产业开发区江苏省无锡市新吴区行创六路7-22",
                                "deliveryBatch": "10:18-11:18",
                                "fastDeliveryDate": "2022-04-19 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "华润万家-新洲花园店",
                                "purchaseNum": 1
                            }
                        },
                        {
                            "productBaseInfo": {
                                "skuId": "10025873559632",
                                "name": "护舒宝奢柔考拉裤 M-L 4片/包",
                                "image": "https://m.360buyimg.com/babel/jfs/t1/155050/28/3855/211596/5f99baffEdb71e6e5/46f717497980daae.jpg",
                                "picUrl": "jfs/t1/155050/28/3855/211596/5f99baffEdb71e6e5/46f717497980daae.jpg",
                                "backUpPics": [],
                                "backUpWords": [],
                                "jdPrice": "23.00",
                                "realStock": true,
                                "pPrice": "23",
                                "pcpPrice": "30",
                                "showStatus": false,
                                "appDiscount": "比PC端省7元",
                                "canSell": true,
                                "useContrast": false,
                                "imgCheck": 0,
                                "plusPrice": "",
                                "areaStock": true,
                                "businessPrice": "",
                                "skuRelaId": "",
                                "opPrice": "23",
                                "spPrice": "",
                                "hideCart": false,
                                "tkPrice": "",
                                "soldOversea": 0,
                                "isCanUseDQ": 1,
                                "isCanUseJQ": 1,
                                "isOverseaPurchase": 0,
                                "classIdL3": 16800,
                                "venderId": 10509076,
                                "classIdL2": 16754,
                                "classIdL1": 16750,
                                "allNum": "",
                                "saleUnit": "",
                                "freeMark": 0,
                                "isSeptax": 0,
                                "nameCn": "",
                                "naFlagImgM": "",
                                "brandId": "",
                                "fare": 0,
                                "atts": [],
                                "spuId": "",
                                "mkPrice": "",
                                "isFzxp": "",
                                "isJx": "",
                                "up": "",
                                "sfPrice": "",
                                "shopId": 0,
                                "shopName": "",
                                "pr": 23
                            },
                            "productConfigInfo": {
                                "copyWriting": "",
                                "copyWritingDown": "",
                                "tag": ""
                            },
                            "productBiInfo": {
                                "biClk": "1#1a6b400e75e16c676dbdb509461daac249395bf1-104-619613#36420966",
                                "bi": {
                                    "ord": null,
                                    "brokerInfo": "eyJwIjoiNjE5NjEzIiwicHJzdGF0ZSI6IjAiLCJwaSI6IjAxMTkzNjgyIiwic291cmNlIjoiMCIsInRhZyI6Ijc4MTQiLCJjc191c2VyIjoiMiIsImV4cGlkIjoiMTA0IiwicmVxc2lnIjoiMWE2YjQwMGU3NWUxNmM2NzZkYmRiNTA5NDYxZGFhYzI0OTM5NWJmMSJ9",
                                    "bRec": null,
                                    "testId": 1,
                                    "alid": "2",
                                    "udi": "N",
                                    "did": "36420966",
                                    "alclk": "1a6b400e75e16c676dbdb509461daac249395bf1-104-619613",
                                    "skuid": null
                                },
                                "hided": false
                            },
                            "productCommentInfo": {
                                "commentCount": "",
                                "goodRate": ""
                            },
                            "extension": {
                                "promoPrice": null,
                                "UsedSPLX": null,
                                "longPicList": null,
                                "longPicType": null,
                                "winsdate": null,
                                "leastPlanAmount": null,
                                "pssx": null
                            },
                            "mcInfo": "16998410-34463614-10025873559632-1000068339#1-0-1014-10509076-10004--#2-jddj-#560-36420966#mainActivity",
                            "mci": {
                                "didi": "560-36420966",
                                "src": "mainActivity",
                                "mcs": "2-jddj-",
                                "mcd": "16998410-34463614-10025873559632-1000068339",
                                "mct": "1-0-1014-10509076-10004--"
                            },
                            "productExtInfo": {
                                "baseFreight": 7,
                                "storeTag": {
                                    "pickup_code": 0,
                                    "pickup_type": 0,
                                    "jddj_store": 1,
                                    "omni_channel_store": 1,
                                    "delivery_mode": 1
                                },
                                "oriPresalePrice": 0,
                                "shopLogo": "/popshop/jfs/t23812/362/2403295549/6879/850c76b1/5b7e1d31Na86b80d0.jpg!cc_80x80",
                                "venderId": 10509076,
                                "storeInitialPrice": "20",
                                "bizStartHours": "09:00",
                                "agingType": 1440,
                                "storeId": 1000068339,
                                "expAmount": 0,
                                "bizEndHours": "21:00",
                                "storeDistance": 52983,
                                "addressDetail": "江苏无锡市江阴市澄江街道江阴青果路14号首层屈臣氏",
                                "deliveryBatch": "10:00-20:00",
                                "fastDeliveryDate": "2022-04-20 00:00:00",
                                "storeBusiness": [
                                    1
                                ],
                                "storeName": "屈臣氏-江阴青果路店"
                            }
                        }
                    ],
                    "deliveryType": "560",
                    "deliveryId": "36420966",
                    "stageET": "",
                    "materialType": "1014"
                }
            ],
            "areaStockStrategy": 1,
            "styleId": 10004,
            "poolStyle": 0,
            "ext": {
                "isLbsStock": 0
            }
        }
    ]
}

[
    {
      "sourceCode": "comhd",
      "privateKey": "111ee6bd-52d1-4baa-a0b0-b327d1422b6b",
      "clientInfo": {
        "source": 0
      },
      "forceBot": 0,
      "mcChannel": 4
    },
    {
      "ids": [
        "06190960"
      ],
      "stage": 0,
      "pin": "jd_506df9b122153",
      "adsDept": 0,
      "num": 0,
      "position": 0
    }
  ]